### ISSUE TITLE
Decryption does not works on browser update

### ISSUE THREAD

**Issue by AmirHosseinKarimi** [Jouissance-seeker/killua#1]
According to `getUniqeBrowserId()` in `useKillua` hook, looks like the encryption salt comes from the browser information.

But, what about if the user updates the browser? The browser version will change and previous items saved in storage can not be decrypted. Also, new items will be saved via new salt!

https://github.com/sys113/killua/blob/7eef7336482b638225fe6ac5ae7734dfb22d7b09/src/hooks/killua.ts#L18-L27

**Comment by hamid-shahsavani** [comment]
Hello, this issue has been resolved.

Now, a randomly generated and encrypted value is stored in local storage and used as a salt-key.

As a result, the key will not change with browser updates.

However, please avoid storing sensitive data in local storage, and the sole purpose of encrypting it is to prevent easy access by regular users and to prevent them from easily modifying its value.

https://github.com/sys113/killua/blob/dcf14fc0cf4ac55e4eb52374b27deef0c2e60a58/src/hooks/killua.ts#L19-L42
