### ISSUE TITLE
Encryption critical issue

### ISSUE THREAD

**Issue by AmirHosseinKarimi** [Jouissance-seeker/killua#2]
Looks like the encryption methodology is misused in the library.

To implement encryption correctly we need to store the encryption key in a secure storage or protect (via password or similar).
But, in the library, we used browser information as the encryption key!
It means the encryption key is not protected or secured! It is publicly available!
Besides that updating the browser can change the encryption key... (#1)

I highly recommend adding a "It's not production ready!" warning to the encryption part of the documentation. Until implementing it in a proper way.

**Comment by wepruve** [comment]
Hello,

Certainly, sensitive data should not be stored on local storage. The purpose of encrypting local storage in this method is to prevent regular users from having direct access to the data stored in local storage and also to prevent them from modifying it directly.

> Looks like the encryption methodology is misused in the library.
> 
> To implement encryption correctly we need to store the encryption key in a secure storage or protect (via password or similar). But, in the library, we used browser information as the encryption key! It means the encryption key is not protected or secured! It is publicly available! Besides that updating the browser can change the encryption key... (#1)
> 
> I highly recommend adding a "It's not production ready!" warning to the encryption part of the documentation. Until implementing it in a proper way.

Hello,

Certainly, sensitive data should not be stored on local storage. The purpose of encrypting local storage in this method is to prevent regular users from having direct access to the data stored in local storage and also to prevent them from modifying it directly.

**Comment by wepruve** [comment]
> Looks like the encryption methodology is misused in the library.
> 
> To implement encryption correctly we need to store the encryption key in a secure storage or protect (via password or similar). But, in the library, we used browser information as the encryption key! It means the encryption key is not protected or secured! It is publicly available! Besides that updating the browser can change the encryption key... (#1)
> 
> I highly recommend adding a "It's not production ready!" warning to the encryption part of the documentation. Until implementing it in a proper way.

Hello,

Certainly, sensitive data should not be stored on local storage. The purpose of encrypting local storage in this method is to prevent regular users from having direct access to the data stored in local storage and also to prevent them from modifying it directly.

**Comment by hamid-shahsavani** [comment]
> Looks like the encryption methodology is misused in the library.
> 
> To implement encryption correctly we need to store the encryption key in a secure storage or protect (via password or similar). But, in the library, we used browser information as the encryption key! It means the encryption key is not protected or secured! It is publicly available! Besides that updating the browser can change the encryption key... (#1)
> 
> I highly recommend adding a "It's not production ready!" warning to the encryption part of the documentation. Until implementing it in a proper way.

Hello,

Certainly, sensitive data should not be stored on local storage. The purpose of encrypting local storage in this method is to prevent regular users from having direct access to the data stored in local storage and also to prevent them from modifying it directly.
